require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/schema.rb'
  TargetRubyVersion: 3.3

Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 30

Lint/EmptyBlock:
   Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/AsciiIdentifiers:
  Exclude:
    - features/**/*

Style/FetchEnvVar:
  Enabled: false
