require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 3.3

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 30

Lint/EmptyBlock:
   Enabled: false